log_level: debug
match_level: 5
field_map:
  party_id: RECORD_ID
  last_name: PRIMARY_NAME_LAST
  first_name: PRIMARY_NAME_FIRST
  gender: GENDER
  birth_date: DATE_OF_BIRTH
  dr_lic_num: DRIVERS_LICENSE_NUMBER
  dr_lic_state: DRIVERS_LICENSE_STATE
  ssn: SSN_NUMBER
  address_1: HOME_ADDR_LINE1
  address_2: HOME_ADDR_LINE2
  city: HOME_ADDR_CITY
  state_code: HOME_ADDR_STATE
  zip_code: HOME_ADDR_POSTAL_CODE
  bus_phone: WORK_PHONE_NUMBER
  home_phone: CELL_PHONE_NUMBER
  email_address: EMAIL_ADDRESS
  otn: OTHER_ID_NUMBER
  party_code: TYPE
filters:
  - NonHuman
  - filter: ValueIs
    field: TYPE
    value: DEF
    inverse: false
